title: VitalidadeAgora
description: Dicas e informações de saúde, suplementos e bem-estar
baseurl: ""  # se usar GitHub Pages no username.github.io, deixa vazio
url: "https://vitalidadeagora.github.io" 
theme: minima
plugins:
  - jekyll-feed
